_target_: pytorch_lightning.Trainer

default_root_dir: ${paths.output_dir}

accelerator: gpu
devices: 1

min_epochs: 100
max_epochs: 500
num_sanity_val_steps: 0
log_every_n_steps: 3
check_val_every_n_epoch: 3