defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

run:
  dir: ${paths.log_dir}/runs/${project_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}

sweep:
  dir: ${paths.log_dir}/${project_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  subdir: ${hydra.job.num}
