defaults:
  - model_checkpoint.yaml
  - early_stopping.yaml
  - model_summary
  - rich_progress_bar.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: 'epoch_{epoch:03d}_vloss{TotalLossval:.4f}_vdice{val/Dice_total:.4f}_vprc{val/PRC_total:.4f}'
  monitor: 'val/PRC_total' 
  mode: 'max'
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: ${callbacks.model_checkpoint.monitor}
  patience: 20
  mode: 'max'  

model_summary:
  max_depth: 0